# HTTP Configuration
http.host=0.0.0.0
http.port=8081

# API Configuration
api.base.path=/api/v1
api.name=food-ordering-api
api.version=v1


# Application Configuration
concursys.host=<replace with you concur System API cloudhub endpoint>
concursys.port=443
concursys.path=/api/concur/flight